name: TermLinky
options:
  bundleIdPrefix: com.termlinky
  deploymentTarget:
    iOS: "17.0"

settings:
  base:
    SWIFT_VERSION: "5.9"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic

targets:
  TermLinky:
    type: application
    platform: iOS
    sources:
      - TermLinky/Sources
      - TermLinky/Assets.xcassets
    settings:
      base:
        INFOPLIST_FILE: Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.termlinky.app
        PRODUCT_NAME: TermLinky
        CODE_SIGN_ENTITLEMENTS: entitlements.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    entitlements:
      path: entitlements.plist
