name: TermLinkky
options:
  bundleIdPrefix: com.termlinky
  deploymentTarget:
    macOS: "14.0"

settings:
  base:
    SWIFT_VERSION: "5.9"
    DEVELOPMENT_TEAM: K993U8H5GX
    CODE_SIGN_STYLE: Automatic

targets:
  TermLinkky:
    type: application
    platform: macOS
    sources:
      - TermLinky/Sources
      - TermLinky/Assets.xcassets
    settings:
      base:
        INFOPLIST_FILE: Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.termlinky.server
        PRODUCT_NAME: TermLinkky
        CODE_SIGN_ENTITLEMENTS: entitlements.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        MACOSX_DEPLOYMENT_TARGET: "14.0"
    entitlements:
      path: entitlements.plist
